apiVersion: v1
kind: Service
metadata:
  name: sqlinjection
spec:
  type: LoadBalancer
  selector:
    app: sqlinjection
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  externalIPs:
  - 10.0.2.15
