FROM php:apache

WORKDIR /var/www/html

COPY ./app/html/. .
 
# --
# -- install mysql and set up root account
# --
RUN apt-get update && apt-get upgrade -y

# Docker phpの設定
RUN docker-php-ext-install mysqli
