apiVersion: v1
data:
  index.html: "    <!DOCTYPE html>\n    <html lang=\"ja\">\n    <head>\n        <meta
    charset=\"UTF-8\">\n        <meta name=\"viewport\" content=\"width=device-width,
    initial-scale=1\">\n\n        <title>サンプルSQLインジェクション</title>\n\n        <link
    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\"
    rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\"
    crossorigin=\"anonymous\">\n        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"
    integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\"
    crossorigin=\"anonymous\"></script>\n    </head>\n    <body>\n        <nav class=\"navbar
    navbar-dark bg-primary\">\n<div class=\"container-fluid\">\n    <a class=\"navbar-brand\">SQLインジェクション
    テストサイト</a>\n</div>\n        </nav>\n\n        <div class=\"container mt-3\" style=\"margin-top:
    10px;>\n\n        <div class=\"card\">\n                <div class=\"card-body\">\n
    \       <h5 class=\"card-title\">SQLインジェクション サンプル</h5>\n        <p class=\"card-text\">下記のフォームに入力することでSQLインジェクションの動作を再現することができる</p>\n
    \       <a href=\"#\" id=\"myInput\" class=\"btn btn-primary\" data-bs-toggle=\"modal\"
    data-bs-target=\"#exampleModal\">\nデータベースの中身をみる\n        </a>\n        </div></div>\n
    \       </div>\n\n<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"
    aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\">\n
    \   <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <h5
    class=\"modal-title\" id=\"exampleModalLabel\">データベースの中身</h5>\n        <button
    type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n
    \     </div>\n      <div class=\"modal-body\">\n        <table class=\"table\">\n
    \     <thead>\n        <tr>\n        <th scope=\"col\">ID</th>\n        <th scope=\"col\">名前</th>\n
    \       <th scope=\"col\">年齢</th>\n        <th scope=\"col\">住所</th>\n        </tr>\n
    \     </thead>\n    <tbody>\n    <tr>\n        <th scope=\"row\">1</th>\n        <td>たろう</td>\n
    \       <td>21</td>\n        <td>東京都新宿区1丁目2番地3</td>\n    </tr>\n    <tr>\n        <th
    scope=\"row\">2</th>\n        <td>じろう</td>\n        <td>43</td>\n        <td>東京都新宿区2丁目3番地4</td>\n
    \   </tr>\n    <tr>\n        <th scope=\"row\">3</th>\n        <td>てつろう</td>\n
    \       <td>8</td>\n        <td>東京都新宿区3丁目4番地5</td>\n    </tr>\n    <tr>\n        <th
    scope=\"row\">4</th>\n        <td>きんたろう</td>\n        <td>80</td>\n        <td>東京都新宿区4丁目5番地6</td>\n
    \   </tr>\n    </tbody>\n      </table>\n      </div>\n      <div class=\"modal-footer\">\n
    \       <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n
    \     </div>\n    </div>\n  </div>\n</div>\n\n        <div class=\"container\"
    style=\"margin-top: 30px;\">\n        <form action=\"sqlsample.php\" method=\"post\">\n
    \   <label for=\"exampleFormControlInput1\" class=\"form-label\">ユーザ名</label>\n
    \   <input type=\"text\" class=\"form-control\" id=\"exampleFormControlInput1\"
    name=\"sql\" >\n        <button type=\"submit\" class=\"btn btn-primary mb-3\"
    style=\"margin-top:5px;\">\n            ユーザ情報表示\n        </button>\n        </form>\n
    \       </div>\n    </body>\n    <script>\n        var myModal = document.getElementById('myModal');\n
    \       document.addEventListener(\"DOMContentLoaded\", function(){\ndocument.getElementById('myInput').addEventListener('shown.bs.modal',
    function () {\n    if(!isStarted){}\n    else{\n        myInput.focus();\n    }\n});\n
    \       });\n        </script> \n</html>\n"
  sqlsample.php: "<?php\n    $content = '';\n    $content = $_POST['sql'];\n\n    $connect_status
    = \"不明\";\n    \n    $link = mysqli_connect('127.0.0.1', 'phpUser', 'myPassword',
    'userinfo');\n    $usernotfound = 0;\n\n    // 接続状況をチェックします\n    if (mysqli_connect_errno())
    {\n        $content = \"再度接続して下さい\";\n        $connect_status = \"接続失敗\";\n    }
    else {\n        $connect_status = \"接続完了\";\n        $username = $content;\n    \n
    \       $query = \"SELECT * FROM user where name = '\";\n        $query .= $username;\n
    \       $query .= \"';\";\n\n        $content = \"\";\n\n        if ($result =
    mysqli_query($link, $query)) {\n                while ($row = mysqli_fetch_assoc($result))
    {\n                $usernotfound = 1;\n                    $content .= $row[\"name\"];\n
    \               $content .= \" \";\n                $content .= $row[\"age\"];\n
    \               $content .= \" \";\n                $content .= $row[\"location\"];\n
    \               $content .= \"</br>\";\n                }\n            if($usernotfound
    == 0){\n                $content = $username.\"は見つかりませんでした\";\n            }\n
    \               // 結果セットを開放\n                mysqli_free_result($result);\n        }else{\n
    \           $content .= $username.\"は見つかりませんでした\";\n        }\n        mysqli_close($link);\n
    \   }\n?>\n\n<!DOCTYPE html>\n<html lang=\"jp\">\n        <head>\n        <meta
    content=\"text/html\" charset=\"utf-8\"/>\n        <meta name=\"viewport\" content=\"width=device-width,
    initial-scale=1\">\n\n                <title>サンプルSQLインジェクション</title>\n\n        <link
    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\"
    rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\"
    crossorigin=\"anonymous\">\n        </head>\n        <body>\n        <nav class=\"navbar
    navbar-dark bg-primary\">\n            <div class=\"container-fluid\">\n                <a
    class=\"navbar-brand\">SQLインジェクション テストサイト</a>\n            </div>\n        </nav>\n\n
    \       <div class=\"container mt-3\" style=\"margin-top: 10px;>\n        <div
    class=\"card\">\n            <div class=\"card-body\">\n                <p class=\"h4\">データベース接続状況
    <?php echo($connect_status); ?></p>\n            </div>\n        </div>\n\n        <div
    class=\"card\">\n        <div class=\"card-body\">\n        <p class=\"h3\">個人情報</p>\n
    \               <p class=\"h5\"><?php echo($content); ?></p>\n        </div>\n
    \       </div>\n        </div>\n        </body>\n</html>\n"
kind: ConfigMap
metadata:
  name: php-config
